In [10]:
import numpy as np
import pandas as pd
from scipy.spatial import distance
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# SOAL 1: EUCLIDEAN & MANHATTAN
print("* Soal 1: Euclidean & Manhattan ")

point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])

dist_euclid = np.linalg.norm(point1 - point2)
dist_manhat = np.abs(point1 - point2).sum()

print("Euclidean distance :", round(dist_euclid, 2))
print("Manhattan distance :", round(dist_manhat, 2))



# Soal 2: SMC & Jaccard
print("\n* Soal 2: SMC & Jaccard ")

bin1 = np.array([1, 0, 1, 0, 1, 1])
bin2 = np.array([1, 1, 0, 0, 1, 0])

match_11 = np.sum((bin1 == 1) & (bin2 == 1))
match_00 = np.sum((bin1 == 0) & (bin2 == 0))
diff_10 = np.sum((bin1 == 1) & (bin2 == 0))
diff_01 = np.sum((bin1 == 0) & (bin2 == 1))

smc_value = (match_11 + match_00) / len(bin1)
jaccard_value = match_11 / (match_11 + diff_10 + diff_01)

print("SMC :", round(smc_value, 2))
print("Jaccard :", round(jaccard_value, 2))


# Soal 3: Cosine similarity
print("\n* Soal 3: Cosine similatity ")

teks = [
    "data science is fun",
    "data mining is fun",
    "machine learning is cool"
]

cv = CountVectorizer()
mat_text = cv.fit_transform(teks)

print("Kata kunci:")
print(cv.get_feature_names_out())

print("\nMatrix:")
print(mat_text.toarray())

cos_matrix = cosine_similarity(mat_text)

print("\nCosine Matrix:")
print(cos_matrix)

print("\nD1-D2 :", cos_matrix[0, 1])
print("D1-D3 :", cos_matrix[0, 2])


# Tugas rumah: Dataset Iris
print("\n=== DATASET IRIS ===")

iris_obj = load_iris()
X = iris_obj.data
kolom = iris_obj.feature_names

df_iris = pd.DataFrame(X, columns=kolom)
print("\nData awal:")
print(df_iris.head())


# Normalisasi
print("\n=== Normalisasi data ===")

scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)

df_norm = pd.DataFrame(X_norm, columns=kolom)
print(df_norm.head())


# CONTOH JARAK
print("\n=== Contoh data ke 0 dan ke 1 ===")

data_a = X_norm[0]
data_b = X_norm[1]

print("Euclidean :", round(distance.euclidean(data_a, data_b), 4))
print("Manhattan :", round(distance.cityblock(data_a, data_b), 4))
print("Minkowski :", round(distance.minkowski(data_a, data_b, 3), 4))


# LOOPING
print("\n=== Looping 5 data pertama ===")

for idx1 in range(5):
    for idx2 in range(idx1 + 1, 5):

        d_e = distance.euclidean(X_norm[idx1], X_norm[idx2])
        d_m = distance.cityblock(X_norm[idx1], X_norm[idx2])
        d_mk = distance.minkowski(X_norm[idx1], X_norm[idx2], 3)

        print(f"\nData {idx1} vs {idx2}")
        print("Euclidean :", f"{d_e:.4f}")
        print("Manhattan :", f"{d_m:.4f}")
        print("Minkowski :", f"{d_mk:.4f}")


# MATRIKS JARAK
print("\n=== Matriks jarak (5x5) ===")

jumlah = len(X_norm)

mat_e = np.zeros((jumlah, jumlah))
mat_m = np.zeros((jumlah, jumlah))
mat_mk = np.zeros((jumlah, jumlah))

for i in range(jumlah):
    for j in range(jumlah):
        mat_e[i, j] = distance.euclidean(X_norm[i], X_norm[j])
        mat_m[i, j] = distance.cityblock(X_norm[i], X_norm[j])
        mat_mk[i, j] = distance.minkowski(X_norm[i], X_norm[j], 3)

print("\nEuclidean Matrix")
print(pd.DataFrame(mat_e[:5, :5]))

print("\nManhattan Matrix")
print(pd.DataFrame(mat_m[:5, :5]))

print("\nMinkowski Matrix")
print(pd.DataFrame(mat_mk[:5, :5]))

* Soal 1: Euclidean & Manhattan 
Euclidean distance : 5.2
Manhattan distance : 9

* Soal 2: SMC & Jaccard 
SMC : 0.5
Jaccard : 0.4

* Soal 3: Cosine similatity 
Kata kunci:
['cool' 'data' 'fun' 'is' 'learning' 'machine' 'mining' 'science']

Matrix:
[[0 1 1 1 0 0 0 1]
 [0 1 1 1 0 0 1 0]
 [1 0 0 1 1 1 0 0]]

Cosine Matrix:
[[1.   0.75 0.25]
 [0.75 1.   0.25]
 [0.25 0.25 1.  ]]

D1-D2 : 0.75
D1-D3 : 0.25

=== DATASET IRIS ===

Data awal:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

=== Normalisasi data ===
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0  